// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(m0spikeFFI)
import m0spikeFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_m0spike_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_m0spike_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureM0spikeInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol ProofSessionProtocol: AnyObject, Sendable {
    
    /**
     * Rules switched on by the app, checked on the phone: "expired", "underage", "country", "unreadable", or nil when all pass.
     */
    func localCheck() throws  -> String?
    
    /**
     * Check the 128-byte answer against the OPRF public key (64 bytes) pinned by the session policy.
     */
    func oprfComplete(response: Data, publicKey: Data) throws 
    
    /**
     * The 64-byte blinded request for the OPRF service.
     */
    func oprfRequest() throws  -> Data
    
    /**
     * Find the CSCA, choose the circuits, build the inputs. `served` lists the circuit versions the verifier serves. Returns the circuit names in
     * proving order. `certs_path` and `leaves_path` are the bundled CSCA files, `root_hex` the pinned CSCA tree root.
     */
    func prepare(certsPath: String, leavesPath: String, rootHex: String, served: [String]) throws  -> [String]
    
    /**
     * Make the proofs. Circuits are `<circuits_dir>/<name>.json`, keys `<vk_dir>/<name>.vk` (made on the Mac at build time, never on the phone), one
     * shared SRS file. Stage C and the linked proof run side by side when `concurrent` (decision 41); chained curves run one after the other.
     * Returns the JSON body for `POST /v1/sessions/<id>/proof`. The inputs are dropped when this returns.
     */
    func prove(circuitsDir: String, vkDir: String, srsPath: String, concurrent: Bool) throws  -> String
    
    /**
     * Timings of the last `prove` (seconds per stage). No passport data.
     */
    func timings()  -> String
    
    /**
     * Overwrite and drop everything held for this session. Safe to call twice.
     */
    func wipe() 
    
}
open class ProofSession: ProofSessionProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_m0spike_fn_clone_proofsession(self.handle, $0) }
    }
    /**
     * `policy_json` is the body of `GET /v1/sessions/<id>/policy`. `sod` and `dg1` come from the chip read.
     */
public convenience init(policyJson: Data, sod: Data, dg1: Data)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_constructor_proofsession_new(
        FfiConverterData.lower(policyJson),
        FfiConverterData.lower(sod),
        FfiConverterData.lower(dg1),uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_m0spike_fn_free_proofsession(handle, $0) }
    }

    

    
    /**
     * Rules switched on by the app, checked on the phone: "expired", "underage", "country", "unreadable", or nil when all pass.
     */
open func localCheck()throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_method_proofsession_local_check(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Check the 128-byte answer against the OPRF public key (64 bytes) pinned by the session policy.
     */
open func oprfComplete(response: Data, publicKey: Data)throws   {try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_method_proofsession_oprf_complete(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(response),
        FfiConverterData.lower(publicKey),uniffiCallStatus
    )
}
}
    
    /**
     * The 64-byte blinded request for the OPRF service.
     */
open func oprfRequest()throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_method_proofsession_oprf_request(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Find the CSCA, choose the circuits, build the inputs. `served` lists the circuit versions the verifier serves. Returns the circuit names in
     * proving order. `certs_path` and `leaves_path` are the bundled CSCA files, `root_hex` the pinned CSCA tree root.
     */
open func prepare(certsPath: String, leavesPath: String, rootHex: String, served: [String])throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_method_proofsession_prepare(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(certsPath),
        FfiConverterString.lower(leavesPath),
        FfiConverterString.lower(rootHex),
        FfiConverterSequenceString.lower(served),uniffiCallStatus
    )
})
}
    
    /**
     * Make the proofs. Circuits are `<circuits_dir>/<name>.json`, keys `<vk_dir>/<name>.vk` (made on the Mac at build time, never on the phone), one
     * shared SRS file. Stage C and the linked proof run side by side when `concurrent` (decision 41); chained curves run one after the other.
     * Returns the JSON body for `POST /v1/sessions/<id>/proof`. The inputs are dropped when this returns.
     */
open func prove(circuitsDir: String, vkDir: String, srsPath: String, concurrent: Bool)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_method_proofsession_prove(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(circuitsDir),
        FfiConverterString.lower(vkDir),
        FfiConverterString.lower(srsPath),
        FfiConverterBool.lower(concurrent),uniffiCallStatus
    )
})
}
    
    /**
     * Timings of the last `prove` (seconds per stage). No passport data.
     */
open func timings() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_m0spike_fn_method_proofsession_timings(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Overwrite and drop everything held for this session. Safe to call twice.
     */
open func wipe()  {try! rustCall() {
        uniffiCallStatus in
    uniffi_m0spike_fn_method_proofsession_wipe(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProofSession: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ProofSession

    public static func lift(_ handle: UInt64) throws -> ProofSession {
        return ProofSession(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ProofSession) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProofSession {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ProofSession, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofSession_lift(_ handle: UInt64) throws -> ProofSession {
    return try FfiConverterTypeProofSession.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofSession_lower(_ value: ProofSession) -> UInt64 {
    return FfiConverterTypeProofSession.lower(value)
}




public struct CircomProof: Equatable, Hashable {
    public var a: G1
    public var b: G2
    public var c: G1
    public var `protocol`: String
    public var curve: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(a: G1, b: G2, c: G1, `protocol`: String, curve: String) {
        self.a = a
        self.b = b
        self.c = c
        self.`protocol` = `protocol`
        self.curve = curve
    }

    

    
}

#if compiler(>=6)
extension CircomProof: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCircomProof: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CircomProof {
        return
            try CircomProof(
                a: FfiConverterTypeG1.read(from: &buf), 
                b: FfiConverterTypeG2.read(from: &buf), 
                c: FfiConverterTypeG1.read(from: &buf), 
                protocol: FfiConverterString.read(from: &buf), 
                curve: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: CircomProof, into buf: inout [UInt8]) {
        FfiConverterTypeG1.write(value.a, into: &buf)
        FfiConverterTypeG2.write(value.b, into: &buf)
        FfiConverterTypeG1.write(value.c, into: &buf)
        FfiConverterString.write(value.`protocol`, into: &buf)
        FfiConverterString.write(value.curve, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCircomProof_lift(_ buf: RustBuffer) throws -> CircomProof {
    return try FfiConverterTypeCircomProof.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCircomProof_lower(_ value: CircomProof) -> RustBuffer {
    return FfiConverterTypeCircomProof.lower(value)
}


public struct CircomProofResult: Equatable, Hashable {
    public var proof: CircomProof
    public var inputs: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(proof: CircomProof, inputs: [String]) {
        self.proof = proof
        self.inputs = inputs
    }

    

    
}

#if compiler(>=6)
extension CircomProofResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCircomProofResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CircomProofResult {
        return
            try CircomProofResult(
                proof: FfiConverterTypeCircomProof.read(from: &buf), 
                inputs: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: CircomProofResult, into buf: inout [UInt8]) {
        FfiConverterTypeCircomProof.write(value.proof, into: &buf)
        FfiConverterSequenceString.write(value.inputs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCircomProofResult_lift(_ buf: RustBuffer) throws -> CircomProofResult {
    return try FfiConverterTypeCircomProofResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCircomProofResult_lower(_ value: CircomProofResult) -> RustBuffer {
    return FfiConverterTypeCircomProofResult.lower(value)
}


public struct G1: Equatable, Hashable {
    public var x: String
    public var y: String
    public var z: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x: String, y: String, z: String) {
        self.x = x
        self.y = y
        self.z = z
    }

    

    
}

#if compiler(>=6)
extension G1: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeG1: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> G1 {
        return
            try G1(
                x: FfiConverterString.read(from: &buf), 
                y: FfiConverterString.read(from: &buf), 
                z: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: G1, into buf: inout [UInt8]) {
        FfiConverterString.write(value.x, into: &buf)
        FfiConverterString.write(value.y, into: &buf)
        FfiConverterString.write(value.z, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeG1_lift(_ buf: RustBuffer) throws -> G1 {
    return try FfiConverterTypeG1.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeG1_lower(_ value: G1) -> RustBuffer {
    return FfiConverterTypeG1.lower(value)
}


public struct G2: Equatable, Hashable {
    public var x: [String]
    public var y: [String]
    public var z: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x: [String], y: [String], z: [String]) {
        self.x = x
        self.y = y
        self.z = z
    }

    

    
}

#if compiler(>=6)
extension G2: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeG2: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> G2 {
        return
            try G2(
                x: FfiConverterSequenceString.read(from: &buf), 
                y: FfiConverterSequenceString.read(from: &buf), 
                z: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: G2, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.x, into: &buf)
        FfiConverterSequenceString.write(value.y, into: &buf)
        FfiConverterSequenceString.write(value.z, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeG2_lift(_ buf: RustBuffer) throws -> G2 {
    return try FfiConverterTypeG2.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeG2_lower(_ value: G2) -> RustBuffer {
    return FfiConverterTypeG2.lower(value)
}


public struct GnarkProofResult: Equatable, Hashable {
    public var proof: String
    public var publicInputs: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(proof: String, publicInputs: String) {
        self.proof = proof
        self.publicInputs = publicInputs
    }

    

    
}

#if compiler(>=6)
extension GnarkProofResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGnarkProofResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GnarkProofResult {
        return
            try GnarkProofResult(
                proof: FfiConverterString.read(from: &buf), 
                publicInputs: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: GnarkProofResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.proof, into: &buf)
        FfiConverterString.write(value.publicInputs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGnarkProofResult_lift(_ buf: RustBuffer) throws -> GnarkProofResult {
    return try FfiConverterTypeGnarkProofResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGnarkProofResult_lower(_ value: GnarkProofResult) -> RustBuffer {
    return FfiConverterTypeGnarkProofResult.lower(value)
}


public struct Halo2ProofResult: Equatable, Hashable {
    public var proof: Data
    public var inputs: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(proof: Data, inputs: Data) {
        self.proof = proof
        self.inputs = inputs
    }

    

    
}

#if compiler(>=6)
extension Halo2ProofResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHalo2ProofResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Halo2ProofResult {
        return
            try Halo2ProofResult(
                proof: FfiConverterData.read(from: &buf), 
                inputs: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: Halo2ProofResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.proof, into: &buf)
        FfiConverterData.write(value.inputs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHalo2ProofResult_lift(_ buf: RustBuffer) throws -> Halo2ProofResult {
    return try FfiConverterTypeHalo2ProofResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHalo2ProofResult_lower(_ value: Halo2ProofResult) -> RustBuffer {
    return FfiConverterTypeHalo2ProofResult.lower(value)
}


public 
enum MoproError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case CircomError(String
    )
    case Halo2Error(String
    )
    case NoirError(String
    )
    case GnarkError(String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension MoproError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoproError: FfiConverterRustBuffer {
    typealias SwiftType = MoproError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoproError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .CircomError(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .Halo2Error(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .NoirError(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .GnarkError(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MoproError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .CircomError(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Halo2Error(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .NoirError(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .GnarkError(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoproError_lift(_ buf: RustBuffer) throws -> MoproError {
    return try FfiConverterTypeMoproError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoproError_lower(_ value: MoproError) -> RustBuffer {
    return FfiConverterTypeMoproError.lower(value)
}



public enum ProofLib: Equatable, Hashable {
    
    case arkworks
    case rapidsnark





}

#if compiler(>=6)
extension ProofLib: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProofLib: FfiConverterRustBuffer {
    typealias SwiftType = ProofLib

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProofLib {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .arkworks
        
        case 2: return .rapidsnark
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ProofLib, into buf: inout [UInt8]) {
        switch value {
        
        
        case .arkworks:
            writeInt(&buf, Int32(1))
        
        
        case .rapidsnark:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofLib_lift(_ buf: RustBuffer) throws -> ProofLib {
    return try FfiConverterTypeProofLib.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofLib_lower(_ value: ProofLib) -> RustBuffer {
    return FfiConverterTypeProofLib.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringSequenceString: FfiConverterRustBuffer {
    public static func write(_ value: [String: [String]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterSequenceString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: [String]] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: [String]]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterSequenceString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}
/**
 * Build the flat witness for a monolith circuit from chip data, ordered by the circuit's own ABI.
 * Passport bytes stay in memory; the result is only ever handed to the prover. Errors carry fixed text, never data.
 */
public func buildWitness(circuitPath: String, sod: Data, dg1: Data, tbsBucket: UInt32, currentDate: UInt64, minAge: UInt8, countries: [String])throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_build_witness(
        FfiConverterString.lower(circuitPath),
        FfiConverterData.lower(sod),
        FfiConverterData.lower(dg1),
        FfiConverterUInt32.lower(tbsBucket),
        FfiConverterUInt64.lower(currentDate),
        FfiConverterUInt8.lower(minAge),
        FfiConverterSequenceString.lower(countries),uniffiCallStatus
    )
})
}
/**
 * Structure-only summary of a chip's SOD (algorithms, sizes, whether DG1 matches). Never returns identity data.
 */
public func describeSod(sod: Data, dg1: Data) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_describe_sod(
        FfiConverterData.lower(sod),
        FfiConverterData.lower(dg1),uniffiCallStatus
    )
})
}
/**
 * You can also customize the bindings by #[uniffi::export]
 * Reference: https://mozilla.github.io/uniffi-rs/latest/proc_macro/index.html
 */
public func moproHelloWorld() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_mopro_hello_world(uniffiCallStatus
    )
})
}
public func generateCircomProof(zkeyPath: String, circuitInputs: String, proofLib: ProofLib)throws  -> CircomProofResult  {
    return try  FfiConverterTypeCircomProofResult_lift(try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_generate_circom_proof(
        FfiConverterString.lower(zkeyPath),
        FfiConverterString.lower(circuitInputs),
        FfiConverterTypeProofLib_lower(proofLib),uniffiCallStatus
    )
})
}
public func verifyCircomProof(zkeyPath: String, proofResult: CircomProofResult, proofLib: ProofLib)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_verify_circom_proof(
        FfiConverterString.lower(zkeyPath),
        FfiConverterTypeCircomProofResult_lower(proofResult),
        FfiConverterTypeProofLib_lower(proofLib),uniffiCallStatus
    )
})
}
public func generateGnarkProof(r1csPath: String, pkPath: String, witnessJson: String)throws  -> GnarkProofResult  {
    return try  FfiConverterTypeGnarkProofResult_lift(try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_generate_gnark_proof(
        FfiConverterString.lower(r1csPath),
        FfiConverterString.lower(pkPath),
        FfiConverterString.lower(witnessJson),uniffiCallStatus
    )
})
}
public func verifyGnarkProof(r1csPath: String, vkPath: String, proofResult: GnarkProofResult)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_verify_gnark_proof(
        FfiConverterString.lower(r1csPath),
        FfiConverterString.lower(vkPath),
        FfiConverterTypeGnarkProofResult_lower(proofResult),uniffiCallStatus
    )
})
}
public func generateHalo2Proof(srsPath: String, pkPath: String, circuitInputs: [String: [String]])throws  -> Halo2ProofResult  {
    return try  FfiConverterTypeHalo2ProofResult_lift(try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_generate_halo2_proof(
        FfiConverterString.lower(srsPath),
        FfiConverterString.lower(pkPath),
        FfiConverterDictionaryStringSequenceString.lower(circuitInputs),uniffiCallStatus
    )
})
}
public func verifyHalo2Proof(srsPath: String, vkPath: String, proof: Data, publicInput: Data)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_verify_halo2_proof(
        FfiConverterString.lower(srsPath),
        FfiConverterString.lower(vkPath),
        FfiConverterData.lower(proof),
        FfiConverterData.lower(publicInput),uniffiCallStatus
    )
})
}
/**
 * Generates a Noir proof with automatic hash function selection
 *
 * This is the main proof generation function that automatically chooses
 * the appropriate hash function based on the intended use case:
 *
 * - `on_chain = true`: Uses Keccak hash for Solidity verifier compatibility
 * - `on_chain = false`: Uses Poseidon hash for better performance
 */
public func generateNoirProof(circuitPath: String, srsPath: String?, inputs: [String], onChain: Bool, vk: Data, lowMemoryMode: Bool)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_generate_noir_proof(
        FfiConverterString.lower(circuitPath),
        FfiConverterOptionString.lower(srsPath),
        FfiConverterSequenceString.lower(inputs),
        FfiConverterBool.lower(onChain),
        FfiConverterData.lower(vk),
        FfiConverterBool.lower(lowMemoryMode),uniffiCallStatus
    )
})
}
/**
 * Same proof as `generate_noir_proof` (Poseidon oracle, ZK on) but safe to call from several threads at once: it never re-initialises the SRS to a smaller size.
 */
public func generateNoirProofShared(circuitPath: String, srsPath: String?, inputs: [String], vk: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_generate_noir_proof_shared(
        FfiConverterString.lower(circuitPath),
        FfiConverterOptionString.lower(srsPath),
        FfiConverterSequenceString.lower(inputs),
        FfiConverterData.lower(vk),uniffiCallStatus
    )
})
}
/**
 * Generates a verification key with automatic hash function selection
 *
 * This function automatically chooses the appropriate hash function based
 * on the intended use case:
 *
 * - `on_chain = true`: Uses Keccak hash for Solidity verifier compatibility
 * - `on_chain = false`: Uses Poseidon hash for better performance
 */
public func getNoirVerificationKey(circuitPath: String, srsPath: String?, onChain: Bool, lowMemoryMode: Bool)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_get_noir_verification_key(
        FfiConverterString.lower(circuitPath),
        FfiConverterOptionString.lower(srsPath),
        FfiConverterBool.lower(onChain),
        FfiConverterBool.lower(lowMemoryMode),uniffiCallStatus
    )
})
}
/**
 * Set up the SRS for a circuit ahead of time (used before running proofs side by side).
 */
public func prepareNoirSrs(circuitPath: String, srsPath: String?)  {try! rustCall() {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_prepare_noir_srs(
        FfiConverterString.lower(circuitPath),
        FfiConverterOptionString.lower(srsPath),uniffiCallStatus
    )
}
}
/**
 * Verifies a Noir proof with automatic hash function selection
 *
 * This function automatically uses the correct verification method based
 * on how the proof was generated:
 *
 * - `on_chain = true`: Verifies Keccak-based proof (Solidity compatible)
 * - `on_chain = false`: Verifies Poseidon-based proof (performance optimized)
 */
public func verifyNoirProof(circuitPath: String, proof: Data, onChain: Bool, vk: Data, lowMemoryMode: Bool)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeMoproError_lift) {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_verify_noir_proof(
        FfiConverterString.lower(circuitPath),
        FfiConverterData.lower(proof),
        FfiConverterBool.lower(onChain),
        FfiConverterData.lower(vk),
        FfiConverterBool.lower(lowMemoryMode),uniffiCallStatus
    )
})
}
/**
 * Load the whole shared SRS file into Barretenberg now, so the first proof does not wait for it (called in the background when the member opens the
 * flow). The shared file holds the points for the largest circuit, so every later proof finds the SRS already big enough and `ensure_srs` does
 * nothing. If a proof starts while this is still running it waits on the same lock and then finds the work done: the setup is never done twice.
 * Cheap to call again; a missing or short file is ignored (the proof path then sets the SRS up itself and reports the real error).
 */
public func warmNoirSrs(srsPath: String)  {try! rustCall() {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_warm_noir_srs(
        FfiConverterString.lower(srsPath),uniffiCallStatus
    )
}
}
/**
 * Spots to try for an issuing state (3 letters from the MRZ; empty or unknown = default order): "back_cover", "photo_page", "front_cover".
 */
public func placementOrder(issuingState: String?) -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_m0spike_fn_func_placement_order(
        FfiConverterOptionString.lower(issuingState),uniffiCallStatus
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_m0spike_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_m0spike_checksum_func_build_witness() != 63379) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_func_describe_sod() != 17817) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_func_mopro_hello_world() != 5389) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_func_generate_circom_proof() != 9745) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_func_verify_circom_proof() != 55312) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_func_generate_gnark_proof() != 24275) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_func_verify_gnark_proof() != 15194) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_func_generate_halo2_proof() != 58063) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_func_verify_halo2_proof() != 50344) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_func_generate_noir_proof() != 16310) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_func_generate_noir_proof_shared() != 37820) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_func_get_noir_verification_key() != 55114) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_func_prepare_noir_srs() != 62889) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_func_verify_noir_proof() != 61617) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_func_warm_noir_srs() != 58927) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_func_placement_order() != 59524) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_method_proofsession_local_check() != 27639) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_method_proofsession_oprf_complete() != 19081) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_method_proofsession_oprf_request() != 48146) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_method_proofsession_prepare() != 63448) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_method_proofsession_prove() != 5607) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_method_proofsession_timings() != 9) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_method_proofsession_wipe() != 34203) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_m0spike_checksum_constructor_proofsession_new() != 37092) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureM0spikeInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all